import { SupportedFormat } from './types';

export const SUPPORTED_EXTENSIONS: Record<string, SupportedFormat> = {
  'obj': SupportedFormat.OBJ,
  'fbx': SupportedFormat.FBX,
  'stl': SupportedFormat.STL,
  'gltf': SupportedFormat.GLTF,
  'glb': SupportedFormat.GLB,
};

export const ENVIRONMENT_PRESETS = [
  'sunset',
  'dawn',
  'night',
  'warehouse',
  'forest',
  'apartment',
  'studio',
  'city',
  'park',
  'lobby',
];

export const INITIAL_VIEWER_SETTINGS = {
  autoRotate: false,
  showSurface: true,
  showWireframe: false,
  environment: 'city',
  intensity: 1.5, // Increased default intensity
  smoothShading: false,
  highQualityLighting: false,
  materialColor: '#b0b0b0',
  wireframeColor: '#60a5fa', // Blue-400
  selectionColor: '#a5a5a5', // Default selection highlight color
  metalness: 0.5,
  roughness: 0.5,
  wireframeRemoveDiagonals: false,
};

export const TRANSLATIONS = {
  zh: {
    appTitle: 'YunLiao 3D',
    subtitle: '可视化套件',
    dragDrop: '拖拽或点击选择 3D 模型',
    dragDropSub: '支持 OBJ, FBX, STL, GLTF, GLB 格式',
    dragActive: '释放文件以上传',
    loading: '模型加载中...',
    controls: '控制面板',
    settings: '设置',
    appearance: '外观',
    modelInfo: '模型信息',
    name: '名称',
    format: '格式',
    size: '大小',
    removeModel: '移除模型',
    autoRotate: '自动旋转',
    showSurface: '显示模型实体',
    showWireframe: '显示线框 (布线)',
    lighting: '光照环境',
    intensity: '光照强度',
    upload: '上传模型',
    screenshot: '截图',
    resetView: '重置视角',
    viewCube: ['右', '左', '顶', '底', '前', '后'],
    // Appearance specific
    materialColor: '材质颜色',
    wireframeColor: '线框颜色',
    selectionColor: '选中高亮颜色',
    metalness: '金属度',
    roughness: '粗糙度',
    materialParams: '材质参数',
    smoothShading: '表面平滑',
    smoothOn: '平滑',
    smoothOff: '不平滑',
    highQualityLighting: '高级光照',
    highQualityOn: '高质预览',
    highQualityOff: '标准预览',
    wireframeRemoveDiagonals: '描边',
    wireframeRemoveDiagonalsOn: '已描边',
    wireframeRemoveDiagonalsOff: '无描边',
  },
  en: {
    appTitle: 'YunLiao 3D',
    subtitle: 'Pro Visualization Suite',
    dragDrop: 'Drag & drop or select a 3D model',
    dragDropSub: 'Supports OBJ, FBX, STL, GLTF, GLB',
    dragActive: 'Drop file to upload',
    loading: 'LOADING MODEL...',
    controls: 'Controls',
    settings: 'Settings',
    appearance: 'Appearance',
    modelInfo: 'Model Info',
    name: 'Name',
    format: 'Format',
    size: 'Size',
    removeModel: 'Remove Model',
    autoRotate: 'Auto Rotate',
    showSurface: 'Show Surface',
    showWireframe: 'Show Wireframe',
    lighting: 'Lighting Environment',
    intensity: 'Intensity',
    upload: 'Upload Model',
    screenshot: 'Screenshot',
    resetView: 'Reset View',
    viewCube: ['Right', 'Left', 'Top', 'Bottom', 'Front', 'Back'],
    // Appearance specific
    materialColor: 'Material Color',
    wireframeColor: 'Wireframe Color',
    selectionColor: 'Selection Color',
    metalness: 'Metalness',
    roughness: 'Roughness',
    materialParams: 'Material Parameters',
    smoothShading: 'Smoothing',
    smoothOn: 'Smooth',
    smoothOff: 'Faceted',
    highQualityLighting: 'High Quality Lighting',
    highQualityOn: 'High Quality',
    highQualityOff: 'Standard',
    wireframeRemoveDiagonals: 'Outline',
    wireframeRemoveDiagonalsOn: 'Outline On',
    wireframeRemoveDiagonalsOff: 'Outline Off',
  }
};